### ISSUE TITLE
Change "default" status for athlete position

### ISSUE THREAD

**Issue by ksdurg** [Cascadia-Connections/gybitg#86]
There is currently a "default" position when selecting an athlete position.  (e.g. forward, guard, etc).  We would l ike to change this required field to reflect something more descriptive than "default".  Any changes to this field/selection will precipitate changes in other files (search functions, etc.)  DoD:  when an athlete can select the new option (not an actual position) and not have the app crash during searches.

**Comment by keithrutler** [comment]
With no contact from other summer Interns, I have reassigned this issue to myself and updated its details. This issue is closely related to issue #95 for Position Select List not showing a space. I have issue #95 figured out, and will be figuring out these issue's changes within the same area of code as #95.

**Comment by keithrutler** [comment]
Meets DoD: with the related pull request for issues #86 and #95, this meets the DoD because the player's Position drop down list has a --Select-- default option now, notifying users to select from the list
